# dist: xenial (the default) or newer required
language: node_js # Node 10 LTS or later required
addons:
  chrome: stable # make Chrome available
before_install:
  - npm install -g @lhci/server@0.1.0
  - npm install -g @lhci/cli@0.3.x # install LHCI
after_success:
  - lhci autorun --upload.target=temporary-public-storage 